/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    accounts: Account;
    banks: Bank;
    currencies: Currency;
    crypto_currencies: CryptoCurrency;
    operations: Operation;
    categories: Category;
    places: Place;
  };
  globals: {};
}
export interface User {
  id: string;
  roles?: ('admin' | 'user')[];
  telegramID?: number;
  accounts?: string[] | Account[];
  operations?: string[] | Operation[];
  categories?: string[] | Category[];
  places?: string[] | Place[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Account {
  id: string;
  type: 'Card' | 'Account' | 'Crypto' | 'Cash';
  name: string;
  balance: number;
  bank?: string | Bank;
  currency: string | Currency;
  cryptoCurrency: string | CryptoCurrency;
  isArchived: boolean;
  includeToBalance: boolean;
  isSavings: boolean;
  owner: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface Bank {
  id: string;
  name?: string;
  owner: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface Currency {
  id: string;
  fullName: string;
  sign: string;
  rateToUSD: number;
  updatedAt: string;
  createdAt: string;
}
export interface CryptoCurrency {
  id: string;
  name: string;
  logoUrl?: string;
  cmcID: number;
  rateToUSD: number;
  updatedAt: string;
  createdAt: string;
}
export interface Operation {
  id: string;
  type: 'Expense' | 'Income' | 'Debt' | 'Transfer';
  amount: number;
  withdrawal: number;
  category?: string | Category;
  accountFrom: string | Account;
  accountTo: string | Account;
  place?: string | Place;
  date?: string;
  comment?: string;
  owner: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface Category {
  id: string;
  name: string;
  parent?: string | Category;
  children?: string[] | Category[];
  isIncome: boolean;
  isExpense: boolean;
  owner: string | User;
}
export interface Place {
  id: string;
  name: string;
  owner: string | User;
}
